#!/usr/bin/env bash

repository=elixir
parent=base
variants=(node browsers)
namespace=cimg
base_version=2024.06-20.04
new_version=2025.05
new_tags=(1.19)
parentTags=(26.2.3 27.2.2)
defaultParentTag=27.2.2
parentSlug=erlang
