#!/usr/bin/env bash

repository=elixir
parent=base
variants=(node browsers)
namespace=cimg
base_version=2026.08-22.04
new_version=2026.08
new_tags=(1.20)
parentTags=(27.3.4 28.5.0 29.0.5)
defaultParentTag=29.0.5
parentSlug=erlang
