#!/usr/bin/env bash

repository=elixir
parent=base
variants=(node browsers)
namespace=cimg
base_version=2024.06-20.04
new_version=2025.10
new_tags=(1.19)
parentTags=(25.3.2 26.2.1 27.3.3)
defaultParentTag=27.3.3
parentSlug=erlang
